agents:
- agent_id: test_agent_1
  name: Test Agent
  model: gpt-4
  enabled: false
  max_concurrent_tasks: 3
  polling_interval: 30
  capabilities:
  - code_review
  - issue_triage
  github_token: null
  api_base_url: null
  custom_settings: {}
  created_at: '2025-10-05T16:33:58.488368'
  updated_at: '2025-10-05T16:33:58.511699'
