repositories:
- repo_id: test_repo_1
  owner: m0nk111
  name: test-repo
  enabled: false
  auto_assign_issues: true
  issue_labels:
  - bug
  - enhancement
  branch_prefix: feat
  require_review: true
  auto_merge: false
  webhook_url: null
  custom_settings: {}
  created_at: '2025-10-05T16:33:58.533853'
  updated_at: '2025-10-05T16:33:58.553366'
