monitoring_enabled: true
monitoring_port: 7997
log_level: INFO
max_log_size: 10000
backup_enabled: true
backup_interval: 86400
notification_email: null
slack_webhook: null
custom_settings: {}
updated_at: '2025-10-11T19:46:02.790331'
