# Trusted GitHub Accounts
# NOTE: This file is DEPRECATED
# All trusted accounts are now managed in config/system/github_accounts.yaml
# 
# Migration: Use AccountManager from engine.core.account_manager
#   manager = AccountManager()
#   trusted = manager.get_trusted_accounts()
#
# This file remains for backwards compatibility but should not be edited.
# Edit config/system/github_accounts.yaml instead.

# DEPRECATED - Use github_accounts.yaml
trusted_agents_source: config/system/github_accounts.yaml
