# Trusted GitHub Accounts
# These accounts can interact with the agent system

trusted_agents:
  - username: m0nk111-post
    role: bot
    description: Bot account for automated GitHub operations (posting, organizing, triage)
    trusted: true
  
  - username: m0nk111-qwen-agent
    role: developer
    description: Qwen-based code generation and development agent
    trusted: true
