trusted_agents:
- username: m0nk111-bot
  role: bot
  description: Main bot account for GitHub automation
  trusted: true
agents:
- agent_id: qwen-main-agent
  name: Qwen Main Agent
  model: qwen2.5-coder:7b
  enabled: true
  max_concurrent_tasks: 1
  polling_interval: 60
  capabilities:
  - code_generation
  - code_review
  - issue_management
  - pr_management
  - documentation
  github_token: null
  api_base_url: null
  custom_settings: {}
  local_shell_enabled: true
  shell_working_dir: /opt/agent-forge
  shell_timeout: 300
  shell_permissions: developer
  model_provider: local
  model_name: qwen2.5-coder:7b
  api_key_name: null
  temperature: 0.7
  max_tokens: 4096
  created_at: '2025-10-07T14:30:00'
  updated_at: '2025-10-07T17:12:37.607049'
