# M0nk111 Qwen Agent Configuration
# Primary code generation and development agent

agent:
  # Agent identification
  agent_id: m0nk111-qwen-agent
  name: M0nk111 Qwen Agent
  role: developer
  
  # Model configuration
  model:
    provider: local
    name: qwen2.5-coder:7b
    base_url: null  # Uses system default
    temperature: 0.7
    max_tokens: 4096
    
  # Capabilities - what this agent can do
  capabilities:
    - code_generation
    - code_review
    - issue_management
    - pr_management
    - documentation
    - refactoring
    - testing
  
  # Execution settings
  execution:
    enabled: true
    max_concurrent_tasks: 1
    polling_interval: 60
    
  # Shell access configuration
  shell:
    enabled: true
    working_dir: /opt/agent-forge
    timeout: 300
    permissions: developer  # Full file/terminal access, no PR merge
    
  # GitHub integration
  github:
    token: null  # Auto-loaded from secrets/agents/m0nk111-qwen-agent.token
    username: m0nk111-qwen-agent
    
  # Custom settings
  custom_settings: {}
  
  # Monitoring
  monitoring:
    enabled: true
    report_interval: 30
    
  # Metadata
  created_at: '2025-10-07T14:30:00'
  updated_at: '2025-10-07T21:15:00'
